"""initial schema

Revision ID: a3abc627b231
Revises: 
Create Date: 2026-09-11 16:13:12.926500
"""

from alembic import op
import sqlalchemy as sa


revision = 'a3abc627b231'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('runtime_type', sa.String(length=16), nullable=False),
    sa.Column('default_port', sa.Integer(), nullable=True),
    sa.Column('healthcheck_type', sa.String(length=24), nullable=False),
    sa.Column('healthcheck_url', sa.String(length=255), nullable=True),
    sa.Column('healthcheck_command', sa.String(length=512), nullable=True),
    sa.Column('healthcheck_port', sa.Integer(), nullable=True),
    sa.Column('healthcheck_expected_status', sa.Integer(), nullable=False),
    sa.Column('healthcheck_timeout', sa.Integer(), nullable=False),
    sa.Column('healthcheck_retries', sa.Integer(), nullable=False),
    sa.Column('healthcheck_interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_hooks', sa.Boolean(), nullable=False),
    sa.Column('allowed_environments', sa.JSON(), nullable=False),
    sa.Column('allowed_runtimes', sa.JSON(), nullable=False),
    sa.Column('allowed_host_group_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_code'), ['code'], unique=True)

    op.create_table('distributed_locks',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributed_locks')),
    sa.UniqueConstraint('key', name=op.f('uq_distributed_locks_key'))
    )
    with op.batch_alter_table('distributed_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributed_locks_expires_at'), ['expires_at'], unique=False)

    op.create_table('environments',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('require_confirmation', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('allow_rollback', sa.Boolean(), nullable=False),
    sa.Column('max_parallel_deployments', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_code'), ['code'], unique=True)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('session_generation', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('user_id', 'name', name='uq_api_tokens_user_name')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('application_versions',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('prerelease', sa.String(length=64), nullable=True),
    sa.Column('build_metadata', sa.String(length=64), nullable=True),
    sa.Column('runtime_type', sa.String(length=16), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('image_tag', sa.String(length=128), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('released_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_versions_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], name=op.f('fk_application_versions_released_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_versions')),
    sa.UniqueConstraint('application_id', 'version', name='uq_application_versions_app_version')
    )
    with op.batch_alter_table('application_versions', schema=None) as batch_op:
        batch_op.create_index('ix_application_versions_application_id', ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_versions_checksum_sha256'), ['checksum_sha256'], unique=False)

    op.create_table('configurations',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_configurations_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_configurations_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations')),
    sa.UniqueConstraint('application_id', 'environment_id', name='uq_configurations_app_env')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurations_application_id'), ['application_id'], unique=False)

    op.create_table('host_groups',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_host_groups_environment_id_environments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_groups'))
    )
    with op.batch_alter_table('host_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_host_groups_name'), ['name'], unique=True)

    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('ssh_keys',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ssh_keys_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_keys')),
    sa.UniqueConstraint('name', name=op.f('uq_ssh_keys_name'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('target_hosts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_username', sa.String(length=32), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('os_name', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('kernel_version', sa.String(length=128), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('memory_total_mb', sa.Integer(), nullable=True),
    sa.Column('memory_available_mb', sa.Integer(), nullable=True),
    sa.Column('disk_total_mb', sa.BigInteger(), nullable=True),
    sa.Column('disk_available_mb', sa.BigInteger(), nullable=True),
    sa.Column('runtime_type', sa.String(length=16), nullable=False),
    sa.Column('runtime_version', sa.String(length=64), nullable=True),
    sa.Column('runtime_rootless', sa.Boolean(), nullable=True),
    sa.Column('kubernetes_context', sa.String(length=128), nullable=True),
    sa.Column('kubernetes_namespace', sa.String(length=63), nullable=True),
    sa.Column('kubernetes_version', sa.String(length=64), nullable=True),
    sa.Column('remote_base_path', sa.String(length=255), nullable=True),
    sa.Column('ssh_host_key_type', sa.String(length=32), nullable=True),
    sa.Column('ssh_host_key', sa.Text(), nullable=True),
    sa.Column('ssh_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('ssh_host_key_status', sa.String(length=24), nullable=False),
    sa.Column('ssh_host_key_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('ssh_host_key_approved_at', sa.DateTime(), nullable=True),
    sa.Column('ssh_pending_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('ssh_pending_host_key', sa.Text(), nullable=True),
    sa.Column('ssh_pending_host_key_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_discovery_at', sa.DateTime(), nullable=True),
    sa.Column('discovery_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_target_hosts_environment_id_environments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ssh_host_key_approved_by_id'], ['users.id'], name=op.f('fk_target_hosts_ssh_host_key_approved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_hosts'))
    )
    with op.batch_alter_table('target_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_hosts_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_target_hosts_name'), ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('application_instances',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('desired_version_id', sa.Integer(), nullable=True),
    sa.Column('desired_state', sa.String(length=16), nullable=False),
    sa.Column('desired_replicas', sa.Integer(), nullable=False),
    sa.Column('desired_updated_at', sa.DateTime(), nullable=True),
    sa.Column('desired_updated_by_id', sa.Integer(), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('actual_version', sa.String(length=64), nullable=True),
    sa.Column('actual_state', sa.String(length=16), nullable=False),
    sa.Column('actual_replicas', sa.Integer(), nullable=True),
    sa.Column('actual_runtime', sa.String(length=16), nullable=True),
    sa.Column('actual_observed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_details', sa.JSON(), nullable=True),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_message', sa.Text(), nullable=True),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_type', sa.String(length=24), nullable=False),
    sa.Column('drift_details', sa.JSON(), nullable=True),
    sa.Column('drift_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_deployment_id', sa.Integer(), nullable=True),
    sa.Column('last_operation_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_instances_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_version_id'], ['application_versions.id'], name=op.f('fk_application_instances_current_version_id_application_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['desired_updated_by_id'], ['users.id'], name=op.f('fk_application_instances_desired_updated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['desired_version_id'], ['application_versions.id'], name=op.f('fk_application_instances_desired_version_id_application_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['target_hosts.id'], name=op.f('fk_application_instances_host_id_target_hosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_deployment_id'], ['deployments.id'], name=op.f('fk_application_instances_last_deployment_id_deployments'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['previous_version_id'], ['application_versions.id'], name=op.f('fk_application_instances_previous_version_id_application_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_instances')),
    sa.UniqueConstraint('application_id', 'host_id', name='uq_app_instances_app_host')
    )
    with op.batch_alter_table('application_instances', schema=None) as batch_op:
        batch_op.create_index('ix_app_instances_actual_state', ['actual_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_instances_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_instances_host_id'), ['host_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=64), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('application_code', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_audit_logs_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['target_hosts.id'], name=op.f('fk_audit_logs_target_id_target_hosts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('configuration_entries',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_entries_configuration_id_configurations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_configuration_entries_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_entries')),
    sa.UniqueConstraint('configuration_id', 'key', name='uq_config_entries_key')
    )
    with op.batch_alter_table('configuration_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_entries_configuration_id'), ['configuration_id'], unique=False)

    op.create_table('configuration_versions',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_versions_configuration_id_configurations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_configuration_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_versions')),
    sa.UniqueConstraint('configuration_id', 'version_number', name='uq_config_versions_number')
    )
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_versions_configuration_id'), ['configuration_id'], unique=False)

    op.create_table('deployment_batches',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('max_parallel', sa.Integer(), nullable=False),
    sa.Column('stop_on_failure', sa.Boolean(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_deployment_batches_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_deployment_batches_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['application_versions.id'], name=op.f('fk_deployment_batches_version_id_application_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_batches')),
    sa.UniqueConstraint('reference', name=op.f('uq_deployment_batches_reference'))
    )
    with op.batch_alter_table('deployment_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_batches_application_id'), ['application_id'], unique=False)

    op.create_table('host_group_members',
    sa.Column('host_group_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_group_id'], ['host_groups.id'], name=op.f('fk_host_group_members_host_group_id_host_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['target_hosts.id'], name=op.f('fk_host_group_members_host_id_target_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('host_group_id', 'host_id', name=op.f('pk_host_group_members'))
    )
    op.create_table('packages',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('manifest_application', sa.String(length=64), nullable=True),
    sa.Column('manifest_version', sa.String(length=64), nullable=True),
    sa.Column('manifest_runtime', sa.String(length=16), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('scanner_result', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_packages_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_packages_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['application_versions.id'], name=op.f('fk_packages_version_id_application_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages')),
    sa.UniqueConstraint('version_id', name=op.f('uq_packages_version_id'))
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_status'), ['status'], unique=False)

    op.create_table('runtime_capabilities',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('runtime_type', sa.String(length=16), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('rootless', sa.Boolean(), nullable=True),
    sa.Column('binary_path', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['target_hosts.id'], name=op.f('fk_runtime_capabilities_host_id_target_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_capabilities')),
    sa.UniqueConstraint('host_id', 'runtime_type', name='uq_runtime_cap_host_runtime')
    )
    with op.batch_alter_table('runtime_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_capabilities_host_id'), ['host_id'], unique=False)

    op.create_table('security_events',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_security_events_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['target_hosts.id'], name=op.f('fk_security_events_target_id_target_hosts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_security_events_timestamp', ['timestamp'], unique=False)

    op.create_table('target_credentials',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('credential_type', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('key_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('key_type', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_target_credentials_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['target_hosts.id'], name=op.f('fk_target_credentials_host_id_target_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_credentials'))
    )
    with op.batch_alter_table('target_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_credentials_host_id'), ['host_id'], unique=False)

    op.create_table('deployments',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('auto_rollback', sa.Boolean(), nullable=False),
    sa.Column('rollback_of_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('preflight_result', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_deployments_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['batch_id'], ['deployment_batches.id'], name=op.f('fk_deployments_batch_id_deployment_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_deployments_environment_id_environments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instance_id'], ['application_instances.id'], name=op.f('fk_deployments_instance_id_application_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['application_versions.id'], name=op.f('fk_deployments_previous_version_id_application_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_deployments_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['deployments.id'], name=op.f('fk_deployments_rollback_of_id_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['target_hosts.id'], name=op.f('fk_deployments_target_id_target_hosts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['application_versions.id'], name=op.f('fk_deployments_version_id_application_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments')),
    sa.UniqueConstraint('reference', name=op.f('uq_deployments_reference'))
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index('ix_deployments_application_id', ['application_id'], unique=False)
        batch_op.create_index('ix_deployments_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_deployments_status', ['status'], unique=False)
        batch_op.create_index('ix_deployments_target_id', ['target_id'], unique=False)

    op.create_table('deployment_approvals',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_deployment_approvals_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_approvals_deployment_id_deployments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_deployment_approvals_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_approvals'))
    )
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_approvals_deployment_id'), ['deployment_id'], unique=False)

    op.create_table('deployment_steps',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_steps_deployment_id_deployments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_steps'))
    )
    with op.batch_alter_table('deployment_steps', schema=None) as batch_op:
        batch_op.create_index('ix_deployment_steps_deployment_id', ['deployment_id'], unique=False)

    op.create_table('lifecycle_operations',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('operation_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('environment_code', sa.String(length=16), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('result_code', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_lifecycle_operations_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_lifecycle_operations_deployment_id_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['application_instances.id'], name=op.f('fk_lifecycle_operations_instance_id_application_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_lifecycle_operations_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['target_hosts.id'], name=op.f('fk_lifecycle_operations_target_id_target_hosts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lifecycle_operations')),
    sa.UniqueConstraint('reference', name=op.f('uq_lifecycle_operations_reference'))
    )
    with op.batch_alter_table('lifecycle_operations', schema=None) as batch_op:
        batch_op.create_index('ix_lifecycle_operations_app_target', ['application_id', 'target_id'], unique=False)
        batch_op.create_index('ix_lifecycle_operations_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_operations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_operations_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_lifecycle_operations_status', ['status'], unique=False)

    op.create_table('health_checks',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_health_checks_deployment_id_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['application_instances.id'], name=op.f('fk_health_checks_instance_id_application_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['lifecycle_operations.id'], name=op.f('fk_health_checks_operation_id_lifecycle_operations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.create_index('ix_health_checks_checked_at', ['checked_at'], unique=False)
        batch_op.create_index('ix_health_checks_instance_id', ['instance_id'], unique=False)

    op.create_table('operation_logs',
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['lifecycle_operations.id'], name=op.f('fk_operation_logs_operation_id_lifecycle_operations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index('ix_operation_logs_operation_id', ['operation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_operation_logs_operation_id')

    op.drop_table('operation_logs')
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_health_checks_instance_id')
        batch_op.drop_index('ix_health_checks_checked_at')

    op.drop_table('health_checks')
    with op.batch_alter_table('lifecycle_operations', schema=None) as batch_op:
        batch_op.drop_index('ix_lifecycle_operations_status')
        batch_op.drop_index(batch_op.f('ix_lifecycle_operations_operation_type'))
        batch_op.drop_index(batch_op.f('ix_lifecycle_operations_job_id'))
        batch_op.drop_index('ix_lifecycle_operations_created_at')
        batch_op.drop_index('ix_lifecycle_operations_app_target')

    op.drop_table('lifecycle_operations')
    with op.batch_alter_table('deployment_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_deployment_steps_deployment_id')

    op.drop_table('deployment_steps')
    with op.batch_alter_table('deployment_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_approvals_deployment_id'))

    op.drop_table('deployment_approvals')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_deployments_target_id')
        batch_op.drop_index('ix_deployments_status')
        batch_op.drop_index(batch_op.f('ix_deployments_job_id'))
        batch_op.drop_index('ix_deployments_created_at')
        batch_op.drop_index('ix_deployments_application_id')

    op.drop_table('deployments')
    with op.batch_alter_table('target_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_credentials_host_id'))

    op.drop_table('target_credentials')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_security_events_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))

    op.drop_table('security_events')
    with op.batch_alter_table('runtime_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_capabilities_host_id'))

    op.drop_table('runtime_capabilities')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_status'))
        batch_op.drop_index(batch_op.f('ix_packages_checksum_sha256'))
        batch_op.drop_index(batch_op.f('ix_packages_application_id'))

    op.drop_table('packages')
    op.drop_table('host_group_members')
    with op.batch_alter_table('deployment_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_batches_application_id'))

    op.drop_table('deployment_batches')
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_versions_configuration_id'))

    op.drop_table('configuration_versions')
    with op.batch_alter_table('configuration_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_entries_configuration_id'))

    op.drop_table('configuration_entries')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_timestamp')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('application_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_instances_host_id'))
        batch_op.drop_index(batch_op.f('ix_application_instances_application_id'))
        batch_op.drop_index('ix_app_instances_actual_state')

    op.drop_table('application_instances')
    op.drop_table('user_roles')
    with op.batch_alter_table('target_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_hosts_name'))
        batch_op.drop_index(batch_op.f('ix_target_hosts_environment_id'))

    op.drop_table('target_hosts')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    op.drop_table('ssh_keys')
    op.drop_table('role_permissions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('host_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_host_groups_name'))

    op.drop_table('host_groups')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_application_id'))

    op.drop_table('configurations')
    with op.batch_alter_table('application_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_versions_checksum_sha256'))
        batch_op.drop_index('ix_application_versions_application_id')

    op.drop_table('application_versions')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_code'))

    op.drop_table('environments')
    with op.batch_alter_table('distributed_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributed_locks_expires_at'))

    op.drop_table('distributed_locks')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_code'))

    op.drop_table('applications')
    # ### end Alembic commands ###
