"""Probe, ProbeRegistrationToken, ProbeKey models."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db


def _now():
    return datetime.now(timezone.utc)


class ProbeRegistrationToken(db.Model):
    """One-time token generated by TenantAdmin to authorise probe registration."""

    __tablename__ = "probe_registration_tokens"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    token: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)
    label: Mapped[str | None] = mapped_column(String(120))
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_by: Mapped[str] = mapped_column(String(36), ForeignKey("users.id"), nullable=False)
    used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    used_by_probe_id: Mapped[str | None] = mapped_column(String(36))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)

    tenant: Mapped["Tenant"] = relationship("Tenant")  # type: ignore[name-defined]
    creator: Mapped["User"] = relationship("User", foreign_keys=[created_by])  # type: ignore[name-defined]

    @property
    def is_valid(self) -> bool:
        return not self.used and self.expires_at > datetime.now(timezone.utc)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "token": self.token,
            "label": self.label,
            "expires_at": self.expires_at.isoformat(),
            "used": self.used,
            "used_at": self.used_at.isoformat() if self.used_at else None,
            "created_at": self.created_at.isoformat(),
        }


class Probe(db.Model):
    __tablename__ = "probes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    uuid: Mapped[str] = mapped_column(String(36), nullable=False, unique=True, index=True,
                                       default=lambda: str(uuid.uuid4()))
    name: Mapped[str | None] = mapped_column(String(120))
    hostname: Mapped[str] = mapped_column(String(255), nullable=False)
    machine_id: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="offline", nullable=False)
    last_seen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    registered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)

    # Crypto — public keys only
    public_sign_key: Mapped[str | None] = mapped_column(String(128))      # Ed25519 public key (hex)
    public_exchange_key: Mapped[str | None] = mapped_column(String(128))  # X25519 public key (hex)
    server_sign_public_key: Mapped[str | None] = mapped_column(String(128))
    server_exchange_public_key: Mapped[str | None] = mapped_column(String(128))
    server_side_fingerprint: Mapped[str | None] = mapped_column(String(128))
    key_provisioned: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    keys_rotated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    agent_version: Mapped[str | None] = mapped_column(String(30))
    platform: Mapped[str | None] = mapped_column(String(30))
    architecture: Mapped[str | None] = mapped_column(String(20))
    docker_version: Mapped[str | None] = mapped_column(String(30))
    enabled: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # Network discovery reported by the probe (interfaces + subnets) and the
    # capture interface chosen from the console for Suricata.
    interfaces: Mapped[list | None] = mapped_column(JSON)
    subnets: Mapped[list | None] = mapped_column(JSON)
    ids_interface: Mapped[str | None] = mapped_column(String(64))
    network_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Operator-supplied metadata (editable by the tenant admin).
    location: Mapped[str | None] = mapped_column(String(255))      # indirizzo
    latitude: Mapped[float | None] = mapped_column(Float)          # coordinata
    longitude: Mapped[float | None] = mapped_column(Float)         # coordinata
    contact_name: Mapped[str | None] = mapped_column(String(120))  # referente
    contact_email: Mapped[str | None] = mapped_column(String(255))
    telegram_id: Mapped[str | None] = mapped_column(String(64))    # opzionale
    notes: Mapped[str | None] = mapped_column(Text)

    registration_token_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("probe_registration_tokens.id")
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now, nullable=False
    )

    tenant: Mapped["Tenant"] = relationship("Tenant", back_populates="probes")  # type: ignore[name-defined]
    tasks: Mapped[list["TaskAssignment"]] = relationship("TaskAssignment", back_populates="probe")  # type: ignore[name-defined]

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "uuid": self.uuid,
            "name": self.name,
            "hostname": self.hostname,
            "machine_id": self.machine_id,
            "status": self.status,
            "last_seen": self.last_seen.isoformat() if self.last_seen else None,
            "registered_at": self.registered_at.isoformat(),
            "public_sign_key": self.public_sign_key,
            "public_exchange_key": self.public_exchange_key,
            "server_side_fingerprint": self.server_side_fingerprint,
            "key_provisioned": self.key_provisioned,
            "agent_version": self.agent_version,
            "platform": self.platform,
            "architecture": self.architecture,
            "enabled": self.enabled,
            "interfaces": self.interfaces or [],
            "subnets": self.subnets or [],
            "ids_interface": self.ids_interface,
            "network_updated_at": self.network_updated_at.isoformat() if self.network_updated_at else None,
            "location": self.location,
            "latitude": self.latitude,
            "longitude": self.longitude,
            "contact_name": self.contact_name,
            "contact_email": self.contact_email,
            "telegram_id": self.telegram_id,
            "notes": self.notes,
        }


class ProbeKey(db.Model):
    """Historical key pairs — tracks rotations."""

    __tablename__ = "probe_keys"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    probe_id: Mapped[str] = mapped_column(String(36), ForeignKey("probes.id", ondelete="CASCADE"), nullable=False)
    tenant_id: Mapped[str] = mapped_column(String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)

    probe_sign_public_key: Mapped[str] = mapped_column(String(128), nullable=False)
    probe_exchange_public_key: Mapped[str] = mapped_column(String(128), nullable=False)
    server_sign_public_key: Mapped[str] = mapped_column(String(128), nullable=False)
    server_exchange_public_key: Mapped[str] = mapped_column(String(128), nullable=False)
    fingerprint: Mapped[str] = mapped_column(String(128), nullable=False)

    active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    probe: Mapped["Probe"] = relationship("Probe")
